kumuluzee:
  datasources:
    - jndi-name: jdbc/CustomersDS
      connection-url: jdbc:postgresql://localhost:5432/pis
      username: postgres
      password: postgres
      pool:
        max-size: 20
  streaming:
    kafka:
      producer:
        bootstrap-servers: 127.0.0.1:9092
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: events.serializer.EventSerializer
      consumer:
        bootstrap-servers: 127.0.0.1:9092
        group-id: group1
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: events.serializer.EventDeserializer