axon:
  axonserver:
    componentName: kumuluz-axon-example
  eventhandling:
    processors:
      giftcard.handler: 11
      product.repo: 1222

kumuluzee:
  datasources:
    - jndi-name: jdbc/testDS
      connection-url: jdbc:postgresql://localhost:5432/test
      username: postgres
      password: postgres
      pool:
        max-size: 20